# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-04 18:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Thing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thing_name', models.CharField(max_length=25)),
                ('thing_cost', models.IntegerField(default=0)),
                ('availability', models.BooleanField(default=True)),
                ('photo', models.ImageField(null=True, upload_to='mythbala/')),
            ],
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField(default=0)),
                ('parent_profile', models.ManyToManyField(to='mythbala.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='thing',
            name='parent_week',
            field=models.ManyToManyField(to='mythbala.Week'),
        ),
    ]
