# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-03 17:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thing',
            fields=[
                ('thing_name', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('thing_cost', models.IntegerField(default=0)),
                ('availability', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('week_number', models.IntegerField(primary_key=True, serialize=False)),
                ('things', models.ManyToManyField(to='mythbala.Thing')),
            ],
        ),
        migrations.AddField(
            model_name='thing',
            name='parent_week',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mythbala.Week'),
        ),
    ]
