# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-04 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mythbala', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='week',
            name='things',
        ),
        migrations.RemoveField(
            model_name='thing',
            name='parent_week',
        ),
        migrations.AddField(
            model_name='thing',
            name='parent_week',
            field=models.ManyToManyField(to='mythbala.Week'),
        ),
    ]
